### ISSUE TITLE
可以提供一个 tccli monitor GetMonitorData 示例用法吗

### ISSUE THREAD

**Issue by xiaoqing-wei** [TencentCloud/tencentcloud-cli#10]
`tccli monitor GetMonitorData help

NAME
        GetMonitorData

DESCRIPTION
        monitor-2018-07-24

USEAGE
        tccli monitor GetMonitorData [--param...]

OPTIONS
        help
        show the tccli monitor GetMonitorData help info

        --profile
        specify a profile name

        --secretId
        specify a SecretId

        --secretKey
        specify a SecretKey

        --region
        identify the region to which the instance you want to work with belongs.

        --endpoint
        specify an access point domain name

        --version
        specify a GetMonitorData api version

        --filter
        specify a filter field

        --timeout
        specify a request timeout

AVAILABLE PARAMS
        --Namespace
        命名空间，每个云产品会有一个命名空间

        --MetricName
        指标名称，各个云产品的详细指标说明请参阅各个产品[监控指标](https://cloud.tencent.com/document/product/248/6140)文档

        --Instances
        实例对象的维度组合

        --Period
        监控统计周期。默认为取值为300，单位为s

        --StartTime
        起始时间，如2018-09-22T19:51:23+08:00

        --EndTime
        结束时间，默认为当前时间。 EndTime不能小于StartTime

`

tccli monitor GetMonitorData --Period 300 --MetricName "base_cpu_usage" --Namespace "qce/cvm" --Instances '["ins-g9kktqy6"]'
会遇到报错，请问可以提供一个示例用法吗
tccli: 'str' object has no attribute 'get'

**Comment by zqfan** [comment]
这个报错不太友好，抱歉了，我看看如何改善下。
这个接口的Instaces实际是个复杂的数据结果，可以参考官网https://cloud.tencent.com/document/product/248/31014
tccli monitor GetMonitorData --Period 300 --MetricName "base_cpu_usage" --Namespace "qce/cvm" --Instances '[{"Dimensions":[{"Name":"InstanceId","Value":"ins-g9kktqy6"}]}]'

**Comment by xiaoqing-wei** [comment]
> 这个报错不太友好，抱歉了，我看看如何改善下。
> 这个接口的Instaces实际是个复杂的数据结果，可以参考官网https://cloud.tencent.com/document/product/248/31014
> tccli monitor GetMonitorData --Period 300 --MetricName "base_cpu_usage" --Namespace "qce/cvm" --Instances '[{"Dimensions":[{"Name":"InstanceId","Value":"ins-g9kktqy6"}]}]'

非常感谢！
