### ISSUE TITLE
怎么参与贡献呢？

### ISSUE THREAD

**Issue by cynial** [TencentCloud/tencentcloud-cli#11]
没看到相关的指引，看了已关掉的 pr，也基本是拒绝的，是不考虑外部的 pr 吗？

**Comment by zqfan** [comment]
跟接口有关的（tccli/service目录）都是生成的，即使合入也会在下一次会被覆盖，因此必定会被拒绝。
非自动生成代码的改动，根据具体功能判断是否能接受
