### ISSUE TITLE
tencentcloud-cli安装过后无法使用

### ISSUE THREAD

**Issue by wangchen-guang** [TencentCloud/tencentcloud-cli#12]
目前安装了cli但未找到tccli客户端
pip3 install tccli
return:
Installing collected packages: jmespath, tencentcloud-sdk-python, tccli
Successfully installed jmespath-0.10.0 tccli-3.0.304.1 tencentcloud-sdk-python-3.0.304
problem:
which tccli
return: /usr/bin/which: no tccli in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

**Comment by ws0416** [comment]
执行pip3 uninstall tccli看一下装到了哪个bin目录下？然后把此bin目录添加到环境变量。
pip3 uninstall tccli
Uninstalling tccli-3.0.304.2:
  Would remove:
    /anaconda3/bin/tccli
    /anaconda3/bin/tccli_completer
    /anaconda3/lib/python3.7/site-packages/tccli-3.0.304.2.dist-info/*
    /anaconda3/lib/python3.7/site-packages/tccli/*
Proceed (y/n)?

**Comment by wangchen-guang** [comment]
everything is ok,thanks
