### ISSUE TITLE
default.configure failed invalid syntax (__init__.py, line 2)

### ISSUE THREAD

**Issue by v7lin** [TencentCloud/tencentcloud-cli#2]
[root@bogon ~]# python --version
Python 2.7.5

[root@bogon ~]# pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)

[root@bogon ~]# tccli version
3.0.30.1

[root@bogon ~]# tccli configure
TencentCloud API secretId[None]: AKID2yiHeo2dFexxxxxxxx
TencentCloud API secretKey[None]: nUK3av65rW1Kyyyyyyyy
region[None]: ap-guangzhou
output[json]: 
tccli: modify file /root/.tccli/default.configure failed invalid syntax (__init__.py, line 2)

**Comment by zqfan** [comment]
请勿在公网上泄漏密钥，请立刻删除您这个密钥，并在控制台上创建并使用新的密钥

**Comment by zqfan** [comment]
请更新至3.0.30.2，pip install --upgrade tccli
