### ISSUE TITLE
tccli工具没有cns接口

### ISSUE THREAD

**Issue by raindylong** [TencentCloud/tencentcloud-cli#3]
我们想用tccli接口直接操作域名解释功能，但是没有发现cns模块。是改成另外一个模块名了么？

谢谢。

**Comment by zqfan** [comment]
tccli下只有支持了api3.0的接口，cns尚未支持api3.0

**Comment by raindylong** [comment]
那只能按cns接口撸一个脚本来实现了，谢谢。
