### ISSUE TITLE
tccli 3.0.556.1 bug：FileNotFoundError: [Errno 2] No such file or directory: '/root/.tccli/log'

### ISSUE THREAD

**Issue by Cleam** [TencentCloud/tencentcloud-cli#38]
今天突然发现一个Gitlab CI错误（昨天之前一直跑的很稳定）：
![image](https://user-images.githubusercontent.com/4132185/147642879-8fc4595e-6e7b-445c-9140-9c93cfab3a04.png)

CI流程就是将代码同步到CDN，然后使用tccli进行刷新，刷新脚本：
```sh
#!/bin/bash

tccli configure set secretId "$(cat /app/cos/sid)" secretKey "$(cat /app/cos/skey)" region ap-beijing output json

tccli cdn PurgePathCache --cli-unfold-argument --endpoint cdn.ap-beijing.tencentcloudapi.com --Paths "$1" --FlushType flush
```

代码同步正常，刷新异常，报错就是上面截图内容。

我试过降级tccli到版本`3.0.555.1`是正常的，应该就是 `tccli==3.0.556.1` 版本新增日志代码导致，上面报错截图也定位到了代码位置`"tccli/log.py", line 9 os.mkdir(logdir)`

**Comment by isnotnull** [comment]
同样的问题，临时在 CI 配置里指定安装低版本才正常。

**Comment by Cleam** [comment]
估计维护者没留意这个issue，我看已经有[修复PR](https://github.com/TencentCloud/tencentcloud-cli/pull/39)提交了，但是没有关联到这个issue。

最新版本：3.0.557.1 应该是没有这个问题了。

**Comment by zqfan** [comment]
问题已解决
