### ISSUE TITLE
发布新版本前不测试依赖的吗？

### ISSUE THREAD

**Issue by LetTTGACO** [TencentCloud/tencentcloud-cli#46]
无语，更新的这个版本安装失败了，我又退回到上一个版本了

<img width="720" alt="wecom-temp-1c8a50db22fc71b67473ac341765f667" src="https://user-images.githubusercontent.com/37357188/153352714-71ac96a3-6952-46d1-a436-01a74b26cb3a.png">

**Comment by LetTTGACO** [comment]
直接使用以下命令会安装报错，没办法我就指定上个tag的版本号了
```bash
pip install tccli
```

**Comment by zqfan** [comment]
tccli和sdk是同时发布的，但是pypi的服务器索引可能会导致依赖的sdk版本找不到，具体多长时间我还不清楚规律，通常是几分钟时间就可以了。
如果使用的是pypi的镜像源，就要看镜像源的同步间隔，脸不好可能会导致依赖的sdk版本在下次同步前都找不到。

**Comment by zqfan** [comment]
我看下如何解决吧

**Comment by LetTTGACO** [comment]
原来是这样，好的呢，谢谢～

**Comment by zqfan** [comment]
忘了同步了，我们已经加入了在tccli发布前检查sdk是否可以下载的步骤了，理论上后续不会再出现类似的问题
