### ISSUE TITLE
tccli ssl UploadCertificate error

### ISSUE THREAD

**Issue by fdkevin0** [TencentCloud/tencentcloud-cli#54]
Get error wrong format when upload a RSA certificate with `tccli ssl UploadCertificate`.
I have tried cat file content or replace `\n` with `\\n` like `awk -v ORS='\\n' '1'`, but not work.
And tried command generate with [API Explorer](https://console.cloud.tencent.com/api/explorer?Product=ssl&Version=2019-12-05&Action=UploadCertificate&SignVersion=), but with same error.
Pure API requests with same certificate are valid.

```shell
❯ tccli --version
3.0.714.1

❯ tccli ssl UploadCertificate --cli-unfold-argument --CertificatePublicKey=$(cat fullchain.cer) --CertificatePrivateKey=$(cat fdke.vin.key)
usage: tccli [options] <command> <subcommand> [<subcommand> ...] [parameters]
To tccli help text, you can run:

  tccli help
  tccli configure help
  tccli service[cvm] help
  tccli service[cvm] action[RunInstances] help

[TencentCloudSDKException] code:FailedOperation.CertificateInvalid message:证书格式错误。 requestId:c7da17ad-8ff8-436d-ba46-9724baf64836
```

**Comment by zqfan** [comment]
--cli-input-json  try this option, it allows you specify parameters though a json file
