### ISSUE TITLE
I get Expecting value: line 624 column 13 (char 14004)

### ISSUE THREAD

**Issue by Heywaht** [TencentCloud/tencentcloud-cli#65]
Hello i cant use any command with tccli all commands get:
Expecting value: line 624 column 13 (char 14004)

**Comment by zqfan** [comment]
please try to uninstall tccli and reinstall it again:
pip uninstall tccli
pip install tccli
if the problem is still not resolved, check the log file under ~/.tccli/log/

**Comment by Heywaht** [comment]
Thanks it work now.
