### ISSUE TITLE
How to use the tccli create A TKE cluster?

### ISSUE THREAD

**Issue by zxDiscovery** [TencentCloud/tencentcloud-cli#7]
I follow the doc https://github.com/TencentCloud/tencentcloud-cli#%E4%BD%BF%E7%94%A8tccli, 
but always got the error `tccli: 'unicode' object has no attribute 'get'`

**Comment by zqfan** [comment]
Currently, if a parameter is a array or a dictionary, it needs a json string input. For example, if a parameter A is array of type B, and type B is a dictionary has a key named KeyFoo, value type is string, then tccli expects input like --A '[{"KeyFoo":"some value"}]'

You can get the parameter list by running `tccli tke CreateCluster help` or check the document https://intl.cloud.tencent.com/document/product/457/32027
