### ISSUE TITLE
TCCLI 在Python3.12.1环境中出现编码问题，请问有解决方法吗？

### ISSUE THREAD

**Issue by CnHack3r** [TencentCloud/tencentcloud-cli#80]
PS C:\Users\huawei> tccli cam AddUser help --detail
usage: tccli [options] <command> <subcommand> [<subcommand> ...] [parameters]
To tccli help text, you can run:

  tccli help
  tccli configure help
  tccli service[cvm] help
  tccli service[cvm] action[RunInstances] help

'gbk' codec can't decode byte 0xb7 in position 77: illegal multibyte sequence
PS C:\Users\huawei> python.exe -V
Python 3.12.1

**Comment by zqfan** [comment]
这是windows中文版 cmd编码问题，将编码从默认的gbk改为utf8即可
